-- Script SQL actualizado para insertar productos de Agroservicio Milagro de Dios
-- Usando proveedores existentes y IDs de marca directos del CSV

-- Mapeo de códigos de marca del CSV a IDs de proveedores existentes
-- Basado en la lista proporcionada:
-- 4	AGRIVETER S.A DE C.V
-- 5	INDUSTRIAS DIPROVA
-- 6	DISZASA DE C.V
-- 7	BUGSTING S.A DE C.V
-- 8	AGROINDUSTRIAS AGRONUTRIX S.A. DE C.V.
-- 9	TECNICA UNIVERSAL SALVADOREÑA, S.A. DE  C.V.
-- 10	SARAM, S.A. DE C.V
-- 11	PRODUCTOS PECUARIOS S.A. DE C.V.
-- 12	AGROSERVICIO EL SURCO, S.A. DE C.V.
-- 13	AGROSELL, S.A. DE C.V.
-- 14	TERRA ALLIANCE, SOCIEDAD ANONIMA DE CAPITAL VARIABLE
-- 15	LABORATORIOS BIOLOGICOS VETERINARIOS S.A. DE C.V.
-- 16	DISTRIBUIDORA UNIPLAST

-- Insertar productos usando proveedores existentes
-- Mapeo: código_marca -> provider_id
-- 40 -> 4 (AGRIVETER)
-- 45 -> 5 (INDUSTRIAS DIPROVA)
-- 5 -> 5 (INDUSTRIAS DIPROVA)
-- 7 -> 7 (BUGSTING)
-- 34 -> 4 (AGRIVETER)
-- 50 -> 5 (INDUSTRIAS DIPROVA)
-- 8 -> 8 (AGROINDUSTRIAS AGRONUTRIX)
-- 49 -> 4 (AGRIVETER)
-- 36 -> 15 (LABORATORIOS BIOLOGICOS VETERINARIOS)
-- 25 -> 12 (AGROSERVICIO EL SURCO)
-- 12 -> 12 (AGROSERVICIO EL SURCO)
-- 32 -> 11 (PRODUCTOS PECUARIOS)
-- 35 -> 15 (LABORATORIOS BIOLOGICOS VETERINARIOS)
-- 57 -> 15 (LABORATORIOS BIOLOGICOS VETERINARIOS)
-- 6 -> 6 (DISZASA)
-- 41 -> 15 (LABORATORIOS BIOLOGICOS VETERINARIOS)
-- 47 -> 15 (LABORATORIOS BIOLOGICOS VETERINARIOS)
-- 29 -> 15 (LABORATORIOS BIOLOGICOS VETERINARIOS)
-- 38 -> 15 (LABORATORIOS BIOLOGICOS VETERINARIOS)
-- 37 -> 15 (LABORATORIOS BIOLOGICOS VETERINARIOS)
-- 17 -> 15 (LABORATORIOS BIOLOGICOS VETERINARIOS)
-- 18 -> 15 (LABORATORIOS BIOLOGICOS VETERINARIOS)
-- 16 -> 16 (DISTRIBUIDORA UNIPLAST)
-- 20 -> 10 (SARAM)
-- 55 -> 16 (DISTRIBUIDORA UNIPLAST)
-- 31 -> 9 (TECNICA UNIVERSAL SALVADOREÑA)
-- 33 -> 6 (DISZASA)
-- 54 -> 14 (TERRA ALLIANCE)
-- 44 -> 13 (AGROSELL)
-- 46 -> 13 (AGROSELL)
-- 14 -> 14 (TERRA ALLIANCE)
-- 9 -> 9 (TECNICA UNIVERSAL SALVADOREÑA)
-- 13 -> 13 (AGROSELL)
-- 30 -> 10 (SARAM)
-- 53 -> 14 (TERRA ALLIANCE)
-- 48 -> 14 (TERRA ALLIANCE)
-- 26 -> 12 (AGROSERVICIO EL SURCO)
-- 27 -> 12 (AGROSERVICIO EL SURCO)
-- 10 -> 10 (SARAM)
-- 43 -> 14 (TERRA ALLIANCE)
-- 56 -> 4 (AGRIVETER)
-- 3 -> 5 (INDUSTRIAS DIPROVA)
-- 22 -> 10 (SARAM)
-- 15 -> 15 (LABORATORIOS BIOLOGICOS VETERINARIOS)
-- 28 -> 6 (DISZASA)
-- 11 -> 11 (PRODUCTOS PECUARIOS)
-- 39 -> 11 (PRODUCTOS PECUARIOS)
-- 19 -> 10 (SARAM)
-- 4 -> 4 (AGRIVETER)
-- 52 -> 14 (TERRA ALLIANCE)
-- 23 -> 10 (SARAM)
-- 58 -> 12 (AGROSERVICIO EL SURCO)
-- 21 -> 10 (SARAM)
-- 24 -> 10 (SARAM)

-- Insertar productos (primera parte)
INSERT IGNORE INTO products (code, name, state, cfiscal, type, price, description, category, provider_id, marca_id, user_id, image, created_at, updated_at) VALUES
('CON-001', 'CONCENTRADO MOR PRECARNOL (INICIO)', 1, 'GRAVADO', 'TERCERO', '36.5', 'CONCENTRADO MOR PRECARNOL (INICIO)', 'CONCENTRADO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-002', 'CONCENTRADO MOR FINCARNOL QUEBRADO(FINAL)', 1, 'GRAVADO', 'TERCERO', '36', 'CONCENTRADO MOR FINCARNOL QUEBRADO(FINAL)', 'CONCENTRADO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-003', 'CONCENTRADO MOR FINCARNOL ENTERO(FINAL)', 1, 'GRAVADO', 'TERCERO', '36', 'CONCENTRADO MOR FINCARNOL ENTERO(FINAL)', 'CONCENTRADO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-004', 'CONCENTRADO MOR  LACTANCIA 18%', 1, 'GRAVADO', 'TERCERO', '22', 'CONCENTRADO MOR  LACTANCIA 18%', 'CONCENTRADO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-005', 'CONCENTRADO MOR LACTANCIA 23%', 1, 'GRAVADO', 'TERCERO', '24', 'CONCENTRADO MOR LACTANCIA 23%', 'CONCENTRADO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-006', 'CONCENTRADO INICIAMOR', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO INICIAMOR', 'CONCENTRADO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-007', 'CONCENTRADO CRECEMOR', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO CRECEMOR', 'CONCENTRADO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-008', 'CONCENTRADO PONEMOR R', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO PONEMOR R', 'CONCENTRADO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-009', 'CONCENTRADO MOR POSTURA GRANJA', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO MOR POSTURA GRANJA', 'CONCENTRADO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-010', 'COMIDA PARA PERRO DOGSTAR ADULTO', 1, 'GRAVADO', 'TERCERO', '1', 'COMIDA PARA PERRO DOGSTAR ADULTO', 'COMIDA PERRO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-011', 'COMIDA PARA PERRO DOGSTAR CACHORRO', 1, 'GRAVADO', 'TERCERO', '1', 'COMIDA PARA PERRO DOGSTAR CACHORRO', 'COMIDA PERRO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('POL-001', 'POLLO ENGORDE BLANCO KIKIRIKI', 1, 'GRAVADO', 'TERCERO', '0', 'POLLO ENGORDE BLANCO KIKIRIKI', 'POLLO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('POL-002', 'POLLO ENGORDE COLOR MEJORADO', 1, 'GRAVADO', 'TERCERO', '0', 'POLLO ENGORDE COLOR MEJORADO', 'POLLO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('POL-003', 'POLLITA PONEDORA ROJA', 1, 'GRAVADO', 'TERCERO', '0', 'POLLITA PONEDORA ROJA', 'POLLO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('POL-004', 'POLLITA ROJA SEXADA', 1, 'GRAVADO', 'TERCERO', '0', 'POLLITA ROJA SEXADA', 'POLLO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-012', 'AFRECHO', 1, 'GRAVADO', 'TERCERO', '0', 'AFRECHO', 'CONCENTRADO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-013', 'CONCENTRADO MOR INICIADOR', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO MOR INICIADOR', 'CONCENTRADO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-014', 'CONCENTRADO MOR FINALIZADOR', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO MOR FINALIZADOR', 'CONCENTRADO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-015', 'CONCENTRADO MOR TERNERINA', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO MOR TERNERINA', 'CONCENTRADO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-016', 'CONCENTRADO CERDIMOR INICIO', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO CERDIMOR INICIO', 'CONCENTRADO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-017', 'CONCENTRADO CERDIMOR DESARROLLO', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO CERDIMOR DESARROLLO', 'CONCENTRADO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-018', 'CONCENTRADO MOR MANTENIMIENTO GANADO 12%', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO MOR MANTENIMIENTO GANADO 12%', 'CONCENTRADO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-019', 'CONCENTRADO CERDIMOR ENGORDE', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO CERDIMOR ENGORDE', 'CONCENTRADO', 4, 40, 1, 'none.jpg', NOW(), NOW()),
('CON-020', 'COMIDA PARA PERRO RANGER', 1, 'GRAVADO', 'TERCERO', '1', 'COMIDA PARA PERRO RANGER', 'COMIDA PERRO', 5, 45, 1, 'none.jpg', NOW(), NOW()),
('CON-021', 'CONCENTRADO POSTURA PLUS', 1, 'GRAVADO', 'TERCERO', '31', 'CONCENTRADO POSTURA PLUS', 'CONCENTRADO', 5, 5, 1, 'none.jpg', NOW(), NOW()),
('CON-022', 'CONCENTRADO INICIO ECO', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO INICIO ECO', 'CONCENTRADO', 5, 5, 1, 'none.jpg', NOW(), NOW()),
('CON-023', 'CONCENTRADO FINAL ECO', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO FINAL ECO', 'CONCENTRADO', 5, 5, 1, 'none.jpg', NOW(), NOW()),
('CON-024', 'CONCENTRADO PARA CONEJO', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO PARA CONEJO', 'CONCENTRADO', 7, 7, 1, 'none.jpg', NOW(), NOW()),
('CON-025', 'CONCENTRADO INICIO', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO INICIO', 'CONCENTRADO', 4, 34, 1, 'none.jpg', NOW(), NOW()),
('CON-026', 'CONCENTRADO FINAL', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO FINAL', 'CONCENTRADO', 4, 34, 1, 'none.jpg', NOW(), NOW()),
('CON-027', 'COMIDA PARA PERRO SHOPER CAN ADULTO', 1, 'GRAVADO', 'TERCERO', '0', 'COMIDA PARA PERRO SHOPER CAN ADULTO', 'COMIDA PERRO', 5, 50, 1, 'none.jpg', NOW(), NOW()),
('CON-028', 'COMIDA PARA PERRO SHOPER CAN CACHORRO', 1, 'GRAVADO', 'TERCERO', '0', 'COMIDA PARA PERRO SHOPER CAN CACHORRO', 'COMIDA PERRO', 5, 50, 1, 'none.jpg', NOW(), NOW()),
('CON-029', 'COMIDA PARA GATO SHOPER CAT', 1, 'GRAVADO', 'TERCERO', '0', 'COMIDA PARA GATO SHOPER CAT', 'COMIDA GATO', 5, 50, 1, 'none.jpg', NOW(), NOW()),
('CON-030', 'COMIDA PARA GATO ALIMIAU', 1, 'GRAVADO', 'TERCERO', '0', 'COMIDA PARA GATO ALIMIAU', 'COMIDA GATO', 8, 8, 1, 'none.jpg', NOW(), NOW());
