-- Script SQL para insertar productos de Agroservicio Milagro de Dios
-- Primero insertar el proveedor si no existe

INSERT IGNORE INTO providers (razonsocial, ncr, nit, email, created_at, updated_at)
VALUES ('Agroservicio Milagro de Dios', 'N/A', 'N/A', 'info@agroserviciomilagro.com', NOW(), NOW());

-- Obtener el ID del proveedor
SET @provider_id = (SELECT id FROM providers WHERE razonsocial = 'Agroservicio Milagro de Dios' LIMIT 1);

-- Insertar marcas (códigos del CSV)
INSERT IGNORE INTO marcas (name, description, status, user_id, created_at, updated_at) VALUES
('Marca 40', 'Marca código 40', 'active', 1, NOW(), NOW()),
('Marca 45', 'Marca código 45', 'active', 1, NOW(), NOW()),
('Marca 5', 'Marca código 5', 'active', 1, NOW(), NOW()),
('Marca 7', 'Marca código 7', 'active', 1, NOW(), NOW()),
('Marca 34', 'Marca código 34', 'active', 1, NOW(), NOW()),
('Marca 50', 'Marca código 50', 'active', 1, NOW(), NOW()),
('Marca 8', 'Marca código 8', 'active', 1, NOW(), NOW()),
('Marca 49', 'Marca código 49', 'active', 1, NOW(), NOW()),
('Marca 36', 'Marca código 36', 'active', 1, NOW(), NOW()),
('Marca 25', 'Marca código 25', 'active', 1, NOW(), NOW()),
('Marca 12', 'Marca código 12', 'active', 1, NOW(), NOW()),
('Marca 32', 'Marca código 32', 'active', 1, NOW(), NOW()),
('Marca 35', 'Marca código 35', 'active', 1, NOW(), NOW()),
('Marca 57', 'Marca código 57', 'active', 1, NOW(), NOW()),
('Marca 6', 'Marca código 6', 'active', 1, NOW(), NOW()),
('Marca 41', 'Marca código 41', 'active', 1, NOW(), NOW()),
('Marca 47', 'Marca código 47', 'active', 1, NOW(), NOW()),
('Marca 29', 'Marca código 29', 'active', 1, NOW(), NOW()),
('Marca 38', 'Marca código 38', 'active', 1, NOW(), NOW()),
('Marca 37', 'Marca código 37', 'active', 1, NOW(), NOW()),
('Marca 17', 'Marca código 17', 'active', 1, NOW(), NOW()),
('Marca 18', 'Marca código 18', 'active', 1, NOW(), NOW()),
('Marca 16', 'Marca código 16', 'active', 1, NOW(), NOW()),
('Marca 20', 'Marca código 20', 'active', 1, NOW(), NOW()),
('Marca 55', 'Marca código 55', 'active', 1, NOW(), NOW()),
('Marca 31', 'Marca código 31', 'active', 1, NOW(), NOW()),
('Marca 33', 'Marca código 33', 'active', 1, NOW(), NOW()),
('Marca 54', 'Marca código 54', 'active', 1, NOW(), NOW()),
('Marca 44', 'Marca código 44', 'active', 1, NOW(), NOW()),
('Marca 46', 'Marca código 46', 'active', 1, NOW(), NOW()),
('Marca 14', 'Marca código 14', 'active', 1, NOW(), NOW()),
('Marca 9', 'Marca código 9', 'active', 1, NOW(), NOW()),
('Marca 13', 'Marca código 13', 'active', 1, NOW(), NOW()),
('Marca 30', 'Marca código 30', 'active', 1, NOW(), NOW()),
('Marca 53', 'Marca código 53', 'active', 1, NOW(), NOW()),
('Marca 48', 'Marca código 48', 'active', 1, NOW(), NOW()),
('Marca 26', 'Marca código 26', 'active', 1, NOW(), NOW()),
('Marca 27', 'Marca código 27', 'active', 1, NOW(), NOW()),
('Marca 10', 'Marca código 10', 'active', 1, NOW(), NOW()),
('Marca 43', 'Marca código 43', 'active', 1, NOW(), NOW()),
('Marca 56', 'Marca código 56', 'active', 1, NOW(), NOW()),
('Marca 3', 'Marca código 3', 'active', 1, NOW(), NOW()),
('Marca 22', 'Marca código 22', 'active', 1, NOW(), NOW()),
('Marca 15', 'Marca código 15', 'active', 1, NOW(), NOW()),
('Marca 28', 'Marca código 28', 'active', 1, NOW(), NOW()),
('Marca 11', 'Marca código 11', 'active', 1, NOW(), NOW()),
('Marca 39', 'Marca código 39', 'active', 1, NOW(), NOW()),
('Marca 19', 'Marca código 19', 'active', 1, NOW(), NOW()),
('Marca 4', 'Marca código 4', 'active', 1, NOW(), NOW()),
('Marca 52', 'Marca código 52', 'active', 1, NOW(), NOW()),
('Marca 23', 'Marca código 23', 'active', 1, NOW(), NOW()),
('Marca 58', 'Marca código 58', 'active', 1, NOW(), NOW()),
('Marca 21', 'Marca código 21', 'active', 1, NOW(), NOW()),
('Marca 24', 'Marca código 24', 'active', 1, NOW(), NOW());

-- Insertar productos (primera parte)
INSERT IGNORE INTO products (code, name, state, cfiscal, type, price, description, category, provider_id, marca_id, user_id, image, created_at, updated_at) VALUES
('CON-001', 'CONCENTRADO MOR PRECARNOL (INICIO)', 1, 'GRAVADO', 'TERCERO', '36.5', 'CONCENTRADO MOR PRECARNOL (INICIO)', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-002', 'CONCENTRADO MOR FINCARNOL QUEBRADO(FINAL)', 1, 'GRAVADO', 'TERCERO', '36', 'CONCENTRADO MOR FINCARNOL QUEBRADO(FINAL)', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-003', 'CONCENTRADO MOR FINCARNOL ENTERO(FINAL)', 1, 'GRAVADO', 'TERCERO', '36', 'CONCENTRADO MOR FINCARNOL ENTERO(FINAL)', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-004', 'CONCENTRADO MOR  LACTANCIA 18%', 1, 'GRAVADO', 'TERCERO', '22', 'CONCENTRADO MOR  LACTANCIA 18%', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-005', 'CONCENTRADO MOR LACTANCIA 23%', 1, 'GRAVADO', 'TERCERO', '24', 'CONCENTRADO MOR LACTANCIA 23%', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-006', 'CONCENTRADO INICIAMOR', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO INICIAMOR', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-007', 'CONCENTRADO CRECEMOR', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO CRECEMOR', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-008', 'CONCENTRADO PONEMOR R', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO PONEMOR R', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-009', 'CONCENTRADO MOR POSTURA GRANJA', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO MOR POSTURA GRANJA', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-010', 'COMIDA PARA PERRO DOGSTAR ADULTO', 1, 'GRAVADO', 'TERCERO', '1', 'COMIDA PARA PERRO DOGSTAR ADULTO', 'COMIDA PERRO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-011', 'COMIDA PARA PERRO DOGSTAR CACHORRO', 1, 'GRAVADO', 'TERCERO', '1', 'COMIDA PARA PERRO DOGSTAR CACHORRO', 'COMIDA PERRO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('POL-001', 'POLLO ENGORDE BLANCO KIKIRIKI', 1, 'GRAVADO', 'TERCERO', '0', 'POLLO ENGORDE BLANCO KIKIRIKI', 'POLLO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('POL-002', 'POLLO ENGORDE COLOR MEJORADO', 1, 'GRAVADO', 'TERCERO', '0', 'POLLO ENGORDE COLOR MEJORADO', 'POLLO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('POL-003', 'POLLITA PONEDORA ROJA', 1, 'GRAVADO', 'TERCERO', '0', 'POLLITA PONEDORA ROJA', 'POLLO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('POL-004', 'POLLITA ROJA SEXADA', 1, 'GRAVADO', 'TERCERO', '0', 'POLLITA ROJA SEXADA', 'POLLO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-012', 'AFRECHO', 1, 'GRAVADO', 'TERCERO', '0', 'AFRECHO', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-013', 'CONCENTRADO MOR INICIADOR', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO MOR INICIADOR', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-014', 'CONCENTRADO MOR FINALIZADOR', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO MOR FINALIZADOR', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-015', 'CONCENTRADO MOR TERNERINA', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO MOR TERNERINA', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-016', 'CONCENTRADO CERDIMOR INICIO', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO CERDIMOR INICIO', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-017', 'CONCENTRADO CERDIMOR DESARROLLO', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO CERDIMOR DESARROLLO', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-018', 'CONCENTRADO MOR MANTENIMIENTO GANADO 12%', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO MOR MANTENIMIENTO GANADO 12%', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-019', 'CONCENTRADO CERDIMOR ENGORDE', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO CERDIMOR ENGORDE', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 40' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-020', 'COMIDA PARA PERRO RANGER', 1, 'GRAVADO', 'TERCERO', '1', 'COMIDA PARA PERRO RANGER', 'COMIDA PERRO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 45' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-021', 'CONCENTRADO POSTURA PLUS', 1, 'GRAVADO', 'TERCERO', '31', 'CONCENTRADO POSTURA PLUS', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 5' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-022', 'CONCENTRADO INICIO ECO', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO INICIO ECO', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 5' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-023', 'CONCENTRADO FINAL ECO', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO FINAL ECO', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 5' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-024', 'CONCENTRADO PARA CONEJO', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO PARA CONEJO', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 7' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-025', 'CONCENTRADO INICIO', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO INICIO', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 34' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-026', 'CONCENTRADO FINAL', 1, 'GRAVADO', 'TERCERO', '0', 'CONCENTRADO FINAL', 'CONCENTRADO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 34' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-027', 'COMIDA PARA PERRO SHOPER CAN ADULTO', 1, 'GRAVADO', 'TERCERO', '0', 'COMIDA PARA PERRO SHOPER CAN ADULTO', 'COMIDA PERRO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 50' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-028', 'COMIDA PARA PERRO SHOPER CAN CACHORRO', 1, 'GRAVADO', 'TERCERO', '0', 'COMIDA PARA PERRO SHOPER CAN CACHORRO', 'COMIDA PERRO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 50' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-029', 'COMIDA PARA GATO SHOPER CAT', 1, 'GRAVADO', 'TERCERO', '0', 'COMIDA PARA GATO SHOPER CAT', 'COMIDA GATO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 50' LIMIT 1), 1, 'none.jpg', NOW(), NOW()),
('CON-030', 'COMIDA PARA GATO ALIMIAU', 1, 'GRAVADO', 'TERCERO', '0', 'COMIDA PARA GATO ALIMIAU', 'COMIDA GATO', @provider_id, (SELECT id FROM marcas WHERE name = 'Marca 8' LIMIT 1), 1, 'none.jpg', NOW(), NOW());


